from copy import deepcopy


SPARSEDRIVE_STAGE1_HYPERPARAMS = {
    "version": "trainval",
    "length": {"trainval": 28130, "mini": 323},
    "total_batch_size": 64,
    "num_gpus": 8,
    "num_epochs": 100,
    "checkpoint_epoch_interval": 20,
    "input_shape": (704, 256),
    "class_names": [
        "car",
        "truck",
        "construction_vehicle",
        "bus",
        "trailer",
        "barrier",
        "motorcycle",
        "bicycle",
        "pedestrian",
        "traffic_cone",
    ],
    "map_class_names": ["ped_crossing", "divider", "boundary"],
    "roi_size": (30, 60),
    "num_sample": 20,
    "fut_ts": 12,
    "fut_mode": 6,
    "ego_fut_ts": 6,
    "ego_fut_mode": 6,
    "queue_length": 4,
    "embed_dims": 256,
    "num_groups": 8,
    "num_decoder": 6,
    "num_single_frame_decoder": 1,
    "num_single_frame_decoder_map": 1,
    "num_map_temp_instances": 0,
    "use_grid_mask": True,
    "grid_mask_use_h": True,
    "grid_mask_use_w": True,
    "grid_mask_rotate": 1,
    "grid_mask_offset": False,
    "grid_mask_ratio": 0.5,
    "grid_mask_mode": 1,
    "grid_mask_prob": 0.7,
    "use_deformable_func": True,
    "strides": [4, 8, 16, 32],
    "num_depth_layers": 3,
    "depth_loss_weight": 0.2,
    "drop_out": 0.1,
    "temporal": True,
    "temporal_map": True,
    "decouple_attn_motion": True,
    "with_quality_estimation": True,
    "task_config": {"with_det": True, "with_map": True, "with_motion_plan": False},
    "kmeans_dir": "./sparsedrive_model/data/kmeans_nuscenes",
    "backbone_pretrained": "model_weights/resnet50-19c8e357.pth",
    "backbone_with_cp": True,
    "fpn_out_channels": 256,
    "fpn_add_extra_convs": "on_output",
    "fpn_in_channels": [256, 512, 1024, 2048],
    "num_cams": 6,
    "deformable_attn_drop": 0.15,
    "deformable_use_camera_embed": True,
    "deformable_residual_mode": "cat",
    "attention_batch_first": True,
    "ffn_pre_norm": "LN",
    "ffn_act_cfg": "ReLU",
    "det_cls_threshold_to_reg": 0.05,
    "det_dn_loss_weight": 5.0,
    "det_gt_cls_key": "gt_labels_3d",
    "det_gt_reg_key": "gt_bboxes_3d",
    "det_gt_id_key": "instance_id",
    "det_with_instance_id": True,
    "det_task_prefix": "det",
    "det_num_anchor": 900,
    "det_num_temp_instances": 600,
    "det_confidence_decay": 0.6,
    "det_feat_grad": False,
    "det_anchor_file": "kmeans_det_900.npy",
    "det_keypoint_num_learnable_pts": 6,
    "det_keypoint_fix_scale": [
        [0, 0, 0],
        [0.45, 0, 0],
        [-0.45, 0, 0],
        [0, 0.45, 0],
        [0, -0.45, 0],
        [0, 0, 0.45],
        [0, 0, -0.45],
    ],
    "det_encoder_vel_dims": 3,
    "det_encoder_embed_dims_decoupled": [128, 32, 32, 64],
    "det_encoder_embed_dims_coupled": 256,
    "det_encoder_in_loops": 1,
    "det_encoder_out_loops_decoupled": 4,
    "det_encoder_out_loops_coupled": 2,
    "det_ffn_num_fcs": 2,
    "det_refine_yaw": True,
    "det_num_dn_groups": 0,
    "det_num_temp_dn_groups": 0,
    "det_dn_noise_scale": [2.0] * 3 + [0.5] * 7,
    "det_max_dn_gt": 32,
    "det_add_neg_dn": True,
    "det_target_cls_weight": 2.0,
    "det_target_box_weight": 0.25,
    "det_target_reg_weights": [2.0] * 3 + [0.5] * 3 + [0.0] * 4,
    "det_loss_cls_weight": 2.0,
    "det_loss_reg_weight": 0.25,
    "det_loss_gamma": 2.0,
    "det_loss_alpha": 0.25,
    "det_loss_reg_weights": [2.0] * 3 + [1.0] * 7,
    "det_cls_allow_reverse": ["barrier"],
    "det_cls_wise_reg_weights": {
        "traffic_cone": [2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0]
    },
    "map_cls_threshold_to_reg": 0.05,
    "map_num_anchor": 100,
    "map_confidence_decay": 0.6,
    "map_feat_grad": True,
    "map_anchor_file": "kmeans_map_100.npy",
    "map_keypoint_num_learnable_pts": 3,
    "map_keypoint_fix_height": (0, 0.5, -0.5, 1, -1),
    "map_keypoint_ground_height": -1.84023,
    "map_loss_cls_weight": 1.0,
    "map_loss_reg_weight": 10.0,
    "map_loss_beta": 0.01,
    "map_reg_weights": [1.0] * 40,
    "map_gt_cls_key": "gt_map_labels",
    "map_gt_reg_key": "gt_map_pts",
    "map_gt_id_key": "map_instance_id",
    "map_with_instance_id": False,
    "map_task_prefix": "map",
    "motion_anchor_file": "kmeans_motion_{fut_mode}.npy",
    "plan_anchor_file": "kmeans_plan_{ego_fut_mode}.npy",
    "motion_tracking_threshold": 0.2,
    "motion_num_decoder_layers": 3,
    "motion_ffn_num_fcs": 2,
    "motion_loss_cls_weight": 0.2,
    "motion_loss_reg_weight": 0.2,
    "plan_loss_cls_weight": 0.5,
    "plan_loss_reg_weight": 1.0,
    "plan_loss_status_weight": 1.0,
    "planning_decoder_use_rescore": True,
    "motion_num_det": 50,
    "motion_num_map": 10,
}


SPARSEDRIVE_STAGE2_OVERRIDES = {
    "total_batch_size": 48,
    "num_epochs": 10,
    "checkpoint_epoch_interval": 10,
    "task_config": {"with_det": True, "with_map": True, "with_motion_plan": True},
    "num_map_temp_instances": 33,
    "load_from": "ckpt/sparsedrive_stage1.pth",
}


def get_stage1_hyperparams():
    return deepcopy(SPARSEDRIVE_STAGE1_HYPERPARAMS)


def get_stage2_hyperparams():
    hyperparams = get_stage1_hyperparams()
    hyperparams.update(deepcopy(SPARSEDRIVE_STAGE2_OVERRIDES))
    return hyperparams


def derive_training_hyperparams(hyperparams):
    batch_size = hyperparams["total_batch_size"] // hyperparams["num_gpus"]
    num_iters_per_epoch = int(
        hyperparams["length"][hyperparams["version"]]
        // (hyperparams["num_gpus"] * batch_size)
    )
    return batch_size, num_iters_per_epoch
